### ISSUE TITLE
Add check for actual authentication method availability

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#120]
Currently, we only check user preferences to determine availability of an authentication method. For example, if user activates mobile token, we show a mobile token UI despite the fact user has no active devices.

We should add a generic `isAvailable` check to authentication method base, that would use user preferences as one of the inputs, but also check the actual method availability based on user and operation data...

```java
boolean isAvailable(String userId, String operationId);
```

**Comment by romanstrobl** [comment]
During the implementation I have found out that it is better to filter steps already in the getOperation() method. Thanks to this filter the information about authMethod availability is already stored in operation steps and one call of Next Step API can be avoided (this is especially important for POWERAUTH_TOKEN method because it calls PowerAuth API to get list of activations per user). 

Furthemore, it seemed more natural to implement the logic for testing authMethod availability centrally (see class AuthMethodAvailabilityService.java), because authMethods may need to know about availability of other authMethods. For instance the OPERATION_REVIEW authMethod needs to know about availability of SMS_KEY and POWERAUTH authMethods during initialization.
