### ISSUE TITLE
Cancel the operation in case invalid operation_id is provided

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow#246]
In `io.getlime.security.powerauth.lib.webflow.authentication.method.init.controller.ApiController`, we have a followin code:

```java
try {
    operation = getOperation();
} catch (AuthStepException ex) {
    // Operation is not available - this state is valid in INIT authentication method, operation was not initialized yet
    // and it will be initialized as a new operation with default form data for a login operation.
}
```

While it cannot do any harm, it may be confusing for the system users - they seem to confirm some operation and suddenly, they are on login, they can go through the login, and operation fails at third party application (on commit).

We should probably cancel the operation at this point.

@romanstrobl Romane, it is surprisingly not a straight-forward change - I will have look into this one...

**Comment by romanstrobl** [comment]
Ok, I think we should differentiate two cases here:
1. operation is not available because it has not been initialized yet and it is initialized in ApiController later on - aka support for the "default" operation
2. operation is not available because the operation ID is invalid - e.g. it the third party creates an operation but we cannot find the operation ID in NS database

**Comment by petrdvorak** [comment]
... I will have a look.
